export const searchCopyByLanguage = {
  en: {
    eyebrow: 'Search',
    heading: 'Find Stories Fast',
    intro: 'Search titles and excerpts across current-language coverage.',
    placeholder: 'Search stories...',
    submit: 'Search',
    emptyPrompt: 'Start typing to search in this language.',
    emptyState: 'No query yet.',
    noResults: 'No matches for',
    tryAnother: 'Try a different keyword.',
    resultSingular: 'result',
    resultPlural: 'results',
    forQuery: 'for',
    page: 'Page',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    searching: 'Searching...',
    unavailable: 'Search is temporarily unavailable.',
    loadFailure: 'We could not load the search index right now.',
  },
  es: {
    eyebrow: 'Buscar',
    heading: 'Encuentra noticias rápido',
    intro: 'Busca títulos y resúmenes en la cobertura de este idioma.',
    placeholder: 'Buscar noticias...',
    submit: 'Buscar',
    emptyPrompt: 'Escribe para buscar en este idioma.',
    emptyState: 'Aún no has escrito una búsqueda.',
    noResults: 'No hay resultados para',
    tryAnother: 'Prueba con otra palabra clave.',
    resultSingular: 'resultado',
    resultPlural: 'resultados',
    forQuery: 'para',
    page: 'Página',
    of: 'de',
    previous: 'Anterior',
    next: 'Siguiente',
    searching: 'Buscando...',
    unavailable: 'La búsqueda no está disponible temporalmente.',
    loadFailure: 'No pudimos cargar el índice de búsqueda en este momento.',
  },
  it: {
    eyebrow: 'Cerca',
    heading: 'Trova rapidamente le notizie',
    intro: 'Cerca nei titoli e nei sommari della copertura in questa lingua.',
    placeholder: 'Cerca notizie...',
    submit: 'Cerca',
    emptyPrompt: 'Scrivi per cercare in questa lingua.',
    emptyState: 'Non hai ancora inserito una ricerca.',
    noResults: 'Nessun risultato per',
    tryAnother: "Prova un'altra parola chiave.",
    resultSingular: 'risultato',
    resultPlural: 'risultati',
    forQuery: 'per',
    page: 'Pagina',
    of: 'di',
    previous: 'Precedente',
    next: 'Successivo',
    searching: 'Ricerca in corso...',
    unavailable: 'La ricerca è temporaneamente non disponibile.',
    loadFailure: 'Non è stato possibile caricare l’indice di ricerca.',
  },
} as const;
